/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DungeonBlock: typeof import('./components/DungeonBlock.vue')['default']
    DungeonEvent: typeof import('./components/DungeonEvent.vue')['default']
    GameOverEvent: typeof import('./components/GameOverEvent.vue')['default']
    HomeInfo: typeof import('./components/HomeInfo.vue')['default']
    HomeMenu: typeof import('./components/HomeMenu.vue')['default']
    MapBlock: typeof import('./components/MapBlock.vue')['default']
    MapEvent: typeof import('./components/MapEvent.vue')['default']
    Package: typeof import('./components/Package.vue')['default']
    PackageItem: typeof import('./components/PackageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
